const String kashitemple = "https://shrikashidham.com/wp-content/uploads/2023/08/1-3-2048x1306.jpg";
const String assiGhat = "https://www.trawell.in/admin/images/upload/090544471Dashaawamedh_Ghat_Main.jpg";
const String dashashwamedh = "https://www.varanasiguru.com/wp-content/uploads/2021/03/Dashashwamedh-Ghat.jpg";
const String manikarnika = "https://www.varanasiguru.com/wp-content/uploads/2020/09/o.png";
const String sankatMochan = "https://www.optimatravels.com/images/varanasi-images/sankat-mochan-temple-800x400.jpg";
const String sarnath = "https://cdn.getyourguide.com/img/tour/64818eab0a871.jpeg/148.jpg";
const String ramnagarFort = "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/06/75/b9/87.jpg";
const String dhamekhStupa = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRih2pfhF1kYi9CCJV4ogm-nm0OJlyBJoHMzQ&s";
const String satyaNarayanTulsimanasmandir = "https://www.tripnight.com/public/thumbs/monuments/4100/NhplSVH05BCK_468_738.jpg";
const String BHU = "https://static.toiimg.com/thumb/msid-41610838,width=1200,height=900/41610838.jpg";
const String durgatempledurgakund = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/f3/83/46/durga-temple-is-near.jpg?w=1200&h=1200&s=1";
const String bharatkalaMuseum = "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/f3/83/46/durga-temple-is-near.jpg?w=1200&h=1200&s=1";
const String bharatMataMandir = "https://travelsetu.com/apps/uploads/new_destinations_photos/destination/2024/01/05/ae4be49d26e5f17fff4472e7b75f2c2b_1000x1000.jpg";
const String shreeAnnaPrunaMandir = "https://kashiyatra.in/wp-content/uploads/2024/03/annapurna-temple-varanasi.jpg";
const String chaukhandiStupa = "https://im.hunt.in/cg/varanasi/City-Guide/chaukhandi-stupa.jpg";
const String kedarGhat = "https://www.tourmyindia.com/states/uttarpradesh/images/kedar-ghat-varanasi.jpg";
const String darbhanga = "https://www.optimatravels.com/images/varanasi-images/darbhanga-ghat-varanasi-800x400.jpg";
const String alamgiri = "https://www.indiaeasytrip.com/states-of-india/alamgir-masjid-varanasi-images.jpg";
const String pnchgangaGhat = "https://www.optimatravels.com/images/varanasi-images/panchganga-ghat-varanasi-up.jpg";
const String manMandirGhat = "https://visitkashi.in/backend/admin/product_images/168128256591.jpg";
const String dashashwamedhGhat = "https://www.varanasiguru.com/wp-content/uploads/2021/03/Dashashwamedh-Ghat.jpg";
const String nepaliTemple = "https://www.trawell.in/admin/images/upload/090544853Nepali_temple.jpg";
const String tulsiGhat = "https://media1.thrillophilia.com/filestore/dac0lyqd7p5ht740yxrnnteldnzc_1549263120_shutterstock_508621837.jpg";
const String Kaalbhairav = "https://cdn1.prayagsamagam.com/media/2023/05/12165742/Kaal-Bhairav-Temple-Varanasi-3.webp";
const String shivalaGhat = "https://i.ytimg.com/vi/D-mWvWiXwHY/maxresdefault.jpg";
const String iskonTemple = "https://static.toiimg.com/thumb/msid-77811345,width-1280,height-720,resizemode-72/77811345.jpg";
const String shribatukBhairavTemple = "https://www.rvatemples.com/wp-content/uploads/2018/03/2-batuk-bhairav-sadhna-904-2.jpg";
const String sarnathMuseum = "https://i1.wp.com/varanasivideos.com/wp-content/uploads/2019/01/Preaching-Buddha-at-Sarnath-Museum.jpg?fit=1600%2C900&ssl=1";
const String tibetanTemple = "https://www.trawell.in/admin/images/upload/471343665Sarnath_tibetan_temple_1.jpg";
const String jantarMantar = "https://www.jantarmantar.org/gallery/varanasiObsGallery/files/v_009.jpg";
const String shivalaGhat1 = "";
const String scindiaghat = "https://www.tourmyindia.com/socialimg/scindia-ghat-varanasi.jpg";
const String harishChandraghat = "https://www.varanasiguru.com/wp-content/uploads/2022/01/samshaan-ghat-varanasi.png";
const String ruchikaArtGallery = "https://www.varanasiguru.com/wp-content/uploads/2022/01/samshaan-ghat-varanasi.png";
const String chaousattighat = "https://as2.ftcdn.net/v2/jpg/01/26/81/29/1000_F_126812933_YUlAQV4jPCOVzm5rw4s0k3WNBS9MvZLK.jpg";
const String manmandirghat = "https://www.tourmyindia.com/states/uttarpradesh/images/man-mandir-ghat-varanasi.jpg";
const String munshighat = "https://www.themaharajaexpress.org/blog/wp-content/uploads/2018/08/Munshi-Ghat-Varanasi.jpg";
const String ranaMahalGhat = "https://media-cdn.tripadvisor.com/media/photo-m/1280/14/c1/19/0f/rana-mahal-ghat.jpg";
const String sarnathdeerPark = "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjqjbu5h1_p2lI0u7yH3RvLaSgU9l_QpdHVbpbXYG_yk308-8Vh8wk8Qn0UfPTtQtORDnp2qKZZRelXPL4hLvFsWQi4g_2TE4KVz_VfPapbUcf94UMB9R3qN45ZekoxeP22WaiJpswBAic/s1600/deer+park.png";
// const String assiGhat = "";
// const String assiGhat = "";
// const String assiGhat = "";
// const String assiGhat = "";
// const String assiGhat = "";
// const String assiGhat = "";const String assiGhat = "";
// const String assiGhat = "";
// const String assiGhat = "";
// const String assiGhat = "";
// const String assiGhat = "";
// const String assiGhat = "";